---
os: linux
dist: bionic

language: node_js
node_js:
  - "lts/*"

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb
  - npm install
  - gem install html-proofer

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - hugo version
  - hugo --minify
  - htmlproofer ${TRAVIS_BUILD_DIR}/public/ --allow-hash-href --url-ignore "/stats.martignoni.net/" --http-status-ignore "404" || true

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete ${TRAVIS_BUILD_DIR}/public/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master

env:
  jobs:
    - PRODUCTION=true
  global:
    - HUGO_RELEASE=0.76.5
    - secure: Z+71a2GG2larWdNwfbBuh+rQN5QqWcj8rEcxT2QyTsuKA/rmfv8omHsSVVk8WkFKCx5iWIcmHCsD09spG0KBhIRGwqMqeAcz29Lsqxu5yUT9HASZDY/liL69VaSt63F8vV7aNlQ7+Xd8Sio2hM/Bb4GnyIhG5RRI+Wr3M4Z1N/KxR6qeG8AjVP11R4yGR6wciXkqy9RIb0RdLI7wp6ODPELRzEQKz5r0PP1fHQuthh60ciCAbW2DCcYZiMnPbu7CXyz0GAMWfN76ZGoyys96dckDzefRQ8IMTqa7BbuzYcZHUkb6d8Th9XLMjE7iDPvlHIkFZGwF5ghwFqEqMKn8COzwtw5PkCwsX/EeutrkrW3yV8BnqbsVrBbKa/OAhj2mpyLawgdqba5Bl/zP8h+SyuG1kN22HoUm7X/IurCNFtJzTyLVE6Yu1ZlaRBZ1IamU5Qltfyb4eQhoCs9YpBV3QUtZUrRzbk1NLDiec84GIloDuK+vcdMgvbMoDAfXwp9WiSbCCA2WBRnJeB+MScf0RV1fznqMp52DX6YA/6OPz10LiTS3kLiouQI/Wy7fjOAib28CkEVSGuyS4U8P5KzkqbDsa3b/2tGQE7UDTkCpMAV4oeKbSKTle/MDDaLwPsBKBAGT63jMfdUdR1r6AfRt7yPvMTZlNR5oCkndluQH8Ek=
    - secure: RKP2RKtXxtUNkH+TS26fi6SAEdvddyfU5PNklpw6bcpCCnJGa1mexjpeyLK/2m1nr6J3PG1MP6Ut7g5//voLsKY7nQpef8hjjhfqqRjA5spNKys/eSzKFdd4LdYDY8ysAxW0rDObmMTa6OIqz3ZxhhHhLSqHVUGUzGJ4R+Mnz5rP5hlsxObQYoyL6tK4bNJKYMf3GKNLuAoVlfdrH1SNFLEoCZy9JuFY3bwql6Ywh15+2gnM8a3HtzXnCqKxzqKhpbVDFK4a+/XQnBl1WLs8JNOYNll3pRc6V0u/odMECjYSu3hYbzf0gq4SNYF3jlYSCJrn02iKz0zDnbyWqkrlJyQFTr5dY/3DiVNpptiy6X+YmqCMbYoWg6X49UnXkn3urx0JuDOno7paN0tywgOmxwbFXLgPlGaAg7Id2la5oW3nyA1r1c6QNbOC7A7QyT2SptlmzRVhDXBFaQfqaS6L2F0s9ai3eHEXpK3VJneJ7md13V+4zItSmWLU7jvbSFRTaZSpuDlsFkskXLngJxhwW51HVStHHHAx3x5cHaKbi0nuqG/7LC7rBK8DrXdbhmc/PmT7aVL/GjwZzpy+tvPAKbeTQOZD5OHOj/A9JIR6bce4APSPJ43Cjra8zgpnLHpgcO0iosJ8AgrFmCWgPQJVjUtnLAtuqRUzrJGvgkjLzac=
    - secure: DFCClWj+JZJuv/pWdx30LO7u8ZUh8FYIYCahXnB0VEVKMSYxd55fAyNgl4UVsxkyHx4YdO0NDKPFZrsKJyeKfIXLFUQlCROZeXdkJBjTuNDJGSQrNyDOM52XgTW7vm5yYTzJD91H2Ly+61CtJJSGdCGon+oDsh3HHod+yAz1DQJxO5pAG0OFcjx0PAphj+oHuYezpf28KNGoGxGK8gcysk7r/CSVqJU5nug/jFK8hdBzrVmmSrLytcFy9MaZto9QXkp2Rh9Dk2m0P7czIdiSAax8MRlmHSqZPcaW8eFmDdnevRA5pr+5t7S3bkE9LMxzYZLcjZTmfgKQSqCe3HX2SCueDofrhKQzYDtGHVCteX3NySJR7hejViaary3qroAKl4Pi8AmVYasG7WNBtYYLjEhK/EWsDnxkW2gsOToI9mZrQwoH9LXwafGUNVdkio1ERSHkXjt8CctVLjeuusUDidrY/2skgTVQ3gm0VYRzfYMYcyVLqYwol3uwLXGe8rCUA8Af7lpQqN+h1LDf9jGeUbDrdqBsYHDg8szQqlqvTYKIodYTsvbG+izcC3+Qiw3t/gQ2TDqMwSl05Jlc83bkMQwM4buhI4N+d3LntatMLrH63A6ctatYe2VVcrlxD1aLze6j263zW/x4rgx7XFr0PgV7EXEr3162FQ1s7ZnV0Vo=

cache:
  directories:
    - node_modules
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

notifications:
  email:
    on_success: never
