---
os: linux
dist: bionic

addons:
  ssh_known_hosts: ${DEPLOY_HOST}

language: node_js
node_js:
  - "lts/*"

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb
  - npm install

script:
  - hugo version
  - gulp

before_deploy:
  - openssl aes-256-cbc -K $encrypted_3761674ceecc_key -iv $encrypted_3761674ceecc_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.67.1
    - secure: r+b9LcCBjC0qMCcJHllRArLrx3siZ4FwyQtHDZK607LE4LFlPHdpJDhTcVqMCwHVXYmpFS64Eu+PzG2XBaJcBNt6w8puiNGAE0RWucaUfKn83P4yGeM9bydkcIFWvZAr2L4WTcoLtXo3Y/P7LSFE/62ptw3X/tQBnwTVOh8Dc/fPI8IDsTbrFMSsijerQczFEpdaaJupY/UYOMaAaTRiEa49n5kwocvtgEEW+m/wDJcRZclV4sBf1ythdV52i69HkLMXOfl3O15B1iOJZq35CnLwfdxF5fU6BqWkH1f/gmKbygrka8fxnZ8KKKysv+BE3LByuJyeadagKDHZ16itv9u7LRuNId8b0/TkuFSqFRFsLzTKEN/eEuSNB/8uxeUyciARC4vRD1R3Kv5Vc1ANW4YvBra/bgGIYwD6CEsbe0SEofdaGnfMW6aetWY4/vDg/rvZGWiL4JzqgYavnOyaz37OQIuavIIhiyhsCP7UdiUSSWKUX6vevrFX4YzMQ5dx62B3ofca+gMDG1tkSvTa5IS2yNt110B1KbtW2PyIbNsvryE/79+8n2a4IuUvBraqGFzLe8vP7HDZDERfEFvqrkJOgo8PiPd4igVKV+2CCV0pos30ZkqLZ+tDuPzQNIo4Yh6tDybHCdo8c2IYNiptLr+Hgt0me+L7FahIthLkia0=
    - secure: QnHEzUiXgasyk0ZbeszG9FHp7evncYPvNkq5SAVMqv4dEZ8SlQtmfjrDmgWZAYtEDjQs5FzVefga2sjiMLfLZi9BOB9m/ukdJ7Q6HB/8SMvHs6JauclJPG3Mqzh7zPC+5mhObCWwNwdzzrvejYvuvTUkv/C0CzRiz0XwMyK3L19vBIdMq1lDdqt1cQIsxMA2yYTf7iJlU/Udr/Qd+rdHSW32EeS7gILtI9Hx2j5T+k9l9dWc+JzQ9af4jpOdYnKOxdl/pYcDZpEXT8TCgwXHhhuN88Xuku8+DqPLW8gZT2qttVUlITGxVlRRPxktq7juJ4UdJgc3s5Q8aW5mG5L6MO+w+mzvyZS6K0N5ZRDLv3Rdn9KO8dT4N6Ot9BLr0HK2/IJX0U1v7uDV4JSq9YMyIeaASynNWsf7I9u+kC5FvQXFKPOIAvCivNc8rGHItwoUbmnSWUuPKNL7ZuzTy224LJa9TuFm5VTlj7pXZiEHcgfea+YSz1TSr3+Ote6TkHiJfGpA8Z7PIRAYKcl8MqBp3EZrVw33poYseAdQnCid/BLROLVrSsXrkGu2niJKcWP2QUpzbe9sFBn3672qV31U7dGGla9rpz+nGglh00Av9s1ZO7sv1LGvsrcfhoaUyWV19EtrDg4ETHUcycjSN5cS5TPk/QxtJeSjnmQL9+00FDU=
    - secure: es2k9F560KcPUmU4PSPM0xX1akelnJCKIJx+hR+NiaMOakbsuWvQLd0fItonKrp91j9SDsQ3A28vxfk+nTRof/pwMgRXggj5ZCteL9C9zu/5sCIzM/lRhrxJTIFQxS/Q+RIpBck3fadHGorI4xMQg6rKnXJdw7kuWsPzL5MPiq9kqFfoDEMXKSFWLnlogFpu2zUcSNedLjf9MP6pF+cQUPvTh4Sm8LKbL4JK6ARPBb0WteHfhl7hf5+4msYwaC3De024yJilcxiK/lKZHsK6ArTsuyBz25nC83Iowbz1QJfzH1iAqoKkY5xPJjNR7DBu7eRF96blX3XDG4gTX6XyZXqJFdkQKZVK7+A1lGbTexbxk/WfRATLJ7iB5QoTN/tk1bU6ss1HhzUdpNAx2X3Xw669lAu/fdOBdcsc4UAsBeL1QTu/0tkTGNsQUha3oIbMi019hE76T7L9QKO6k9OuunDz7bTjtEm87/Usr31fQZDlGR+Gz8QH7eETFBp63B5PJTDSMf2ywlCplyzs2Qq/ixoBT3XWyiqYZAV6LXOMz+aACqlmQ6GqO6OMHhFXfGL/l6W/kL/xOdpJI7B4+Jd+OSZ9gGJcOXErk+muA7AoVPpULlXb4buC9ZJEG+gd8Sme6M+InRsHono7xctUXsl4KG1iHWJ5STierrqvpPn1aG0=

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
