baseurl: https://blog.martignoni.net/
title: Perspectives
theme:
  - hugo-cloak-email
languageCode: fr-ch
# Set site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage: fr
# Set summary length.
summaryLength: 250
# Customize footnote return links.
footnoteReturnLinkContents: ↩
# Set number of posts per page.
paginate: 5

# Enable robots.txt generation.
enableRobotsTXT: true

# Open absolute links in a new window or tab.
#hrefTargetBlank: true

#googleAnalytics:
#disqusShortname:

# Enable menu system for lazy bloggers.
SectionPagesMenu: main

params:
  description: Enseignant, spécialiste du e-learning, expert en numérisation, fan de Moodle et geek du logiciel libre. Je développe et maintiens la MoodleBox.
  author: Nicolas Martignoni
  powered_by:
  github: martignoni
  twitter: nmartignoni

  # Enable Matomo analytics by entering your tracking code
  matomoAnalytics:
    siteid: 4
    matomoroot: "stats.martignoni.net" # Do not add slashes

outputs:
  home: ["HTML", "JSON", "RSS"]
  section: [ "HTML", "RSS" ]
  page: ["HTML"]

permalinks:
  posts: /:year/:month/:slug/

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
    disableInlineCSS: true
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true
